name: Deploy Flask App to Vultr

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to Server using Password Authentication
        run: |
          sshpass -p "3fM*h+x9ChtwaGL9" ssh -o StrictHostKeyChecking=no root@139.84.176.196  "mkdir -p /var/www/your_app"
          sshpass -p "3fM*h+x9ChtwaGL9" scp -r ./* root@139.84.176.196:/var/www/your_app
          sshpass -p "3fM*h+x9ChtwaGL9" ssh -o StrictHostKeyChecking=no root@139.84.176.196 "bash /var/www/your_app/deploy.sh"
